### ISSUE TITLE
Unity log error when trying to time jump

### ISSUE THREAD

**Issue by ayogi108** [RoboPhred/cultist-speedy#2]
Hey, not sure if you're still interested in working on this but I'll try anyways :)

From the log:

[Message:   BepInEx] BepInEx 5.4.5.0 - cultistsimulator
[Info   :   BepInEx] Running under Unity v2020.1.2.8073916
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 16.1]
[Info   :   BepInEx] Loading [CultistRebind 1.0.1]
[Info   :   BepInEx] Loading [CultistTimejump 1.0.0]
[Message:   BepInEx] Chainloader startup complete
>>>>>>>>>> Cultist Simulator Version: 2021.1.b.2
OS: Windows 10  (10.0.0) 64bit
Processor: AMD Ryzen 5 1600 Six-Core Processor  Count: 12
Graphics: 7171/NVIDIA GeForce GTX 1060 6GB/NVIDIA/Direct3D 11.0 [level 11.1]/3072 Shader: 50
Memory: system - 16318 graphics - 3072

No error in BepInEx log, but this error shows up in Unity log at the moment of me pressing "F" in game:

    MissingMethodException: void Heart.AdvanceTime(single)
      at CultistTimejump.CultistTimejumpPlugin.Update () [0x00019] in <31f14635cc29415c8e5c4edea36ec26d>:0 
     
    (Filename: <31f14635cc29415c8e5c4edea36ec26d> Line: 0)

Tried looking in the source code but I can't determine which part to even look at.

****EDIT

So, to just move things along, I got on an older version of Cultist Simulator (2020.6.a.1_(38654)) and the plugin is working as intended. Which makes me conclude that something in the newest version broke the plugin. I would appreciate it if we can debug this together! <3

****EDIT2
After a little more investigation, I noticed there is big file size jump starting at v2020.11.b.1
v2020.10e2 is 210.3 MB while
v2020.11.b.1 is 303.5 MB.

When I tested the plugin on v2020.11.b.1, it was not working with the same error in Unity log.

**Comment by RoboPhred** [comment]
I'm sorry for missing this issue for a year, but I just fixed this today.  Have fun, if you still play Cult Sim :).
